name = "zallery"
description = "Gallery theme for zola"
license = "MIT"
homepage = "https://github.com/gamingrobot/zallery"
min_version = "0.4.0"
demo = ""

[extra]

[author]
name = "Morgan Creekmore"
homepage = "https://creekmore.dev"